### ISSUE TITLE
can you add heartbeat support？

### ISSUE THREAD

**Issue by cnbryan** [Meoqan/Vaser#1]
can you add heartbeat support？

**Comment by Meoqan** [comment]
Hi @cnbryan 

Thank you for using my library.
I have added heartbeat support in the next version 1.1.23.
The new version must be tested before it can be released.
You can find the new configuration settings in 
`Vaser.Options.EnableHeartbeat`
and
`Vaser.Options.HeartbeatMilliseconds`

Thank you.
Best regards

**Comment by Meoqan** [comment]
The version 1.1.23 has been released.
