### ISSUE TITLE
how to find a client in the server?

### ISSUE THREAD

**Issue by cnbryan** [Meoqan/Vaser#2]
Server.LinkList.Find(xxxxxx)?    USE LINQ?
use this by hashcode or anything?
--------

**Comment by Meoqan** [comment]
Hello @cnbryan 
what would you like to do? 
Here are a few possibilities of finding clients(links):
You can save the link on a new connection in your client object 
```
public static void OnNewLink(object p, LinkEventArgs e)
{
    MyClient client = new MyClient(){ link = e.lnk};
    client.link
}
```
and attach your object to the link
```
e.lnk.AttachedID = client.Id;
e.lnk.AttachedObject = client;
```
so you can access your object directly over the link on a new packet, here you do not need to search
```
static void OnSystemPacket(object p, PacketEventArgs e)
{
   MyClient c = (MyClient)e.lnk.AttachedObject;
   If(c != null){
      //…
   };
}
```
the last possibility is, if you want to send data to other clients:
with IDPool you can generate unique Ids 
`static IDPool myIdPool = new IDPool(100000);`
Then you can store the unique Id in the link 
```
e.lnk.AttachedID = myIdPool.GetFreeID(); // on new link
myIdPool.DisposeID(e.lnk.AttachedID); // on disconnecting link
```
with this unique Id you can store your links in a hashtable or a fast array
```
static Hashtable Linktable = new Hashtable();
Linktable.Add(e.lnk.AttachedID, e.lnk);
```
when you receive a packet for another client you can access the client with the id.
(A better way is, to access your client object directly with the unique Id)
```
// this packet is from client one for client two
Link myLink = (Link)Linktable[e.pak.ObjectID]; 
MyClient c = (MyClient)myLink.AttachedObject; // and get your object from the link
```


Best regards
