### ISSUE TITLE
What is the exact license of this project?

### ISSUE THREAD

**Issue by quangdang9** [Meoqan/Vaser#3]
Hello,
I see two MIT & GNU license files. So what is the exact license of this project?

**Comment by Meoqan** [comment]
Hello @gauanh,
This Project uses both licenses. Simply use that license that fits best to your solution. If you use the MIT license, your app needs not be GNU license compliant.
I want to support Open Source, Closed Source as well commercial use cases.
Best regards

**Comment by quangdang9** [comment]
Ya it's work awesome thank you.
